config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'pages/patient_search' => 'pages#patientSearchPage', as: "search"
  
  get 'pages/doctor' => 'pages#doctorView', as: "doctor"
  get 'pages/medical' => 'pages#medicalView', as: "medical"
  get 'pages/office' => 'pages#officeView', as: "office"
  get 'pages/volunteer' => 'pages#volunteerView', as: "volunteer"
  get 'pages_patient_results' => "pages#pagesPatientResults", as: "pages_patient_results"
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  
  #let the pass controller do the necessary route directing
  root :to => 'pass#index'  
  resources :pages 
  #resources :pages do
    #resources :treatment do 
       #resources :schedules
    #end 
  #end


  #new   /pages/:page_id/treatment/:treatment_id/schedules(.:format)
  #create /pages/:page_id/treatment(.:format)
  
#=begin  
  #PATIENT CUSTOM ROUTES EDIT UPDATE
    get '/pages/:id/edit/edit_patient', to: 'pages#edit_patient', as: :edit_patient
    match "pages/:id/update/update_patient" => "pages#update_patient", as: :update_patient, via: [:patch, :post]

    get '/pages/:id/edit/edit_admittance', to: 'pages#edit_admittance', as: :edit_admittance
    match "pages/:id/update/update_admittance" => "pages#update_admittance", as: :update_admittance, via: [:patch, :post]

    get '/pages/:id/edit/edit_discharge', to: 'pages#edit_discharge', as: :edit_discharge
    match "pages/:id/update/update_discharge" => "pages#update_discharge", as: :update_discharge, via: [:patch, :post]

    get '/pages/:patient_id/discharge/:id/edit/edit_bill', to: 'pages#edit_bill', as: :edit_bill
    match "pages/:patient_id/discharge/:id/update/update_bill" => "pages#update_bill", as: :update_bill, via: [:patch, :post]

    get '/pages/:id/edit/edit_contact', to: 'pages#edit_contact', as: :edit_contact
    match "pages/:id/update/update_contact" => "pages#update_contact", as: :update_contact, via: [:patch, :post]

    get '/pages/:id/edit/edit_physician', to: 'pages#edit_physician', as: :edit_physician
    match "pages/:id/update/update_physician" => "pages#update_physician", as: :update_physician, via: [:patch, :post]

    get '/pages/:id/edit/edit_location', to: 'pages#edit_location', as: :edit_location
    match "pages/:id/update/update_location" => "pages#update_location", as: :update_location, via: [:patch, :post]

    get '/pages/:id/edit/edit_emergency_contact', to: 'pages#edit_emergency_contact', as: :edit_emergency_contact
    match "pages/:id/update/update_emergency_contact" => "pages#update_emergency_contact", as: :update_emergency_contact, via: [:patch, :post]

    get '/pages/:id/edit/edit_insurance', to: 'pages#edit_insurance', as: :edit_insurance
    match "pages/:id/update/update_insurance" => "pages#update_insurance", as: :update_insurance, via: [:patch, :post]

    get '/pages/:id/edit/edit_treatment', to: 'pages#edit_treatment', as: :edit_treatment
    match "pages/:id/update/update_treatment" => "pages#update_treatment", as: :update_treatment, via: [:patch, :post]
    
  
    
    #/pages/:id/treatment/:id/create/create_dr_note(.:format)
    #/treatments/:treatment_id/schedules/:id(.:format)

    #Nested edits and updates (schedule, prescriptions, doctor notes, nurse notes)
    #get '/pages/treatment/:treatment_id/edit/schedule/:id/edit_schedule', to: 'pages#edit_schedule', as: :edit_schedule
    #match "/pages/treatment/:treatment_id/update/schedule/:id/update_schedule" => "pages#update_schedule", as: :update_schedule, via: [:patch, :post]
    

    get '/pages/:patient_id/treatment/:treatment_id/edit_schedule/:schedule_id', to: 'pages#edit_schedule', as: :edit_schedule
    match "pages/:patient_id/treatment/:treatment_id/update_schedule/:schedule_id" => "pages#update_schedule", as: :update_schedule, via: [:patch, :post]

    
    get '/pages/:patient_id/treatment/:treatment_id/edit_prescription/:prescription_id', to: 'pages#edit_prescription', as: :edit_prescription
    match "pages/:patient_id/treatment/:treatment_id/update_prescription/:prescription_id" => "pages#update_prescription", as: :update_prescription, via: [:patch, :post]


    get '/pages/:patient_id/treatment/:treatment_id/edit_dr_note/:dr_id', to: 'pages#edit_dr_note', as: :edit_dr_note
    match "pages/:patient_id/treatment/:treatment_id/update_dr_note/:dr_id" => "pages#update_dr_note", as: :update_dr_note, via: [:patch, :post]

    get '/pages/:patient_id/treatment/:treatment_id/edit_n_note/:n_id', to: 'pages#edit_n_note', as: :edit_n_note
    match "pages/:patient_id/treatment/:treatment_id/update_n_note/:n_id" => "pages#update_n_note", as: :update_n_note, via: [:patch, :post]







    get 'pages/:patient_id/bill/:bill_id/edit_charge/:charge_id', to: 'pages#edit_charge', as: :edit_charge
    match "pages/:patient_id/bill/:bill_id/update_charge/:charge_id" => "pages#update_charge", as: :update_charge, via: [:patch, :post]
        
    #end of nested edits and updates

    #Adding new records
  
    get '/pages/:id/new_physician', to: 'pages#new_physician', as: :create_physician
    match "/pages/:id/new_physician" => "pages#create_physician", as: :new_physician, :via => [:patch, :post]

    get '/pages/:id/new_location', to: 'pages#new_location', as: :create_location
    match "/pages/:id/new_location" => "pages#create_location", as: :new_location, :via => [:patch, :post]

    get '/pages/:id/new_insurance', to: 'pages#new_insurance', as: :create_insurance
    match "/pages/:id/new_insurance" => "pages#create_insurance", as: :new_insurance, :via => [:patch, :post]

    get '/pages/:id/new_emergency_contact', to: 'pages#new_emergency_contact', as: :create_emergency_contact
    match "/pages/:id/new_emergency_contact" => "pages#create_emergency_contact", as: :new_emergency_contact, :via => [:patch, :post]

    get '/pages/:id/new_contact', to: 'pages#new_contact', as: :create_contact
    match "/pages/:id/new_contact" => "pages#create_contact", as: :new_contact, :via => [:patch, :post]

    get '/pages/:id/new_discharge', to: 'pages#new_discharge', as: :create_discharge
    match "/pages/:id/new_discharge" => "pages#create_discharge", as: :new_discharge, :via => [:patch, :post]

    get '/pages/:id/new_treatment', to: 'pages#new_treatment', as: :create_treatment
    match "/pages/:id/new_treatment" => "pages#create_treatment", as: :new_treatment, :via => [:patch, :post]

    get '/pages/:id/treatment/:id/new_schedule', to: 'pages#new_schedule', as: :create_schedule
    match "/pages/:id//treatment/:id/new_schedule" => "pages#create_schedule", as: :new_schedule, :via => [:patch, :post]
    
    get '/pages/:id/treatment/:id/new_dr_note', to: 'pages#new_dr_note', as: :create_dr_note
    match "/pages/:id//treatment/:id/new_dr_note" => "pages#create_dr_note", as: :new_dr_note, :via => [:patch, :post]
    
    get '/pages/:id/treatment/:id/new_n_note', to: 'pages#new_n_note', as: :create_n_note
    match "/pages/:id/treatment/:id/new_n_note" => "pages#create_n_note", as: :new_n_note, :via => [:patch, :post]
    
    get '/pages/:id/treatment/:id/new_prescription', to: 'pages#new_prescription', as: :create_prescription
    match "/pages/:id//treatment/:id/new_prescription" => "pages#create_prescription", as: :new_prescription, :via => [:patch, :post]
    
    get '/pages/:id/discharge/:id/new_bill', to: 'pages#new_bill', as: :create_bill
    match "/pages/:id//discharge/:id/new_bill" => "pages#create_bill", as: :new_bill, :via => [:patch, :post]
    
    get '/pages/:id/discharge/:id/new_charge', to: 'pages#new_charge', as: :create_charge
    match "/pages/:id//discharge/:id/new_charge" => "pages#create_charge", as: :new_charge, :via => [:patch, :post]
    
#=end

  #If a route isn't recognized then let error controller handle it, this needs to be on the last line
    get '*path' => 'error_routes#routing'
end

app/views/pages/edit_admittance.html.erb
<div class="container">
  <% if @recordLocation == "admittance" %>
  <form action="/pages/<%= @patient.id %>/update/update_admittance" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <p><%= debug @admittance %></p>
      <label>Date</label>
       <input type="text" class="form-control datepicker" name="admittance[date]" value="<%= @patient.admittance.date %>">
    </div>
    
    <div class="form-group">
      <label>Time</label>
        <div class='input-group date' id="datetimepicker3">
            <input type="text" class="form-control timepicker" name="admittance[time]" value="<%= @patient.admittance.time.strftime("%I:%M%p") %>">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-time"></span>
            </span>
        </div>
    </div>
    
    <div class="form-group">
      <label>Reason</label>
      <input type="text" class="form-control" name="admittance[reason]" value="<%= @patient.admittance.reason %>">
    </div>
    
    <div class="form-group">
      <div class="button_choose_show_action">
        <p><input type="submit" class="btn btn-primary" style="margin-right: 10px;" value="Update"></p>
        <p><%= link_to "Back", page_path(@patient), html_options = {class: "btn btn-success"} %></p>
      </div>
    </div>
  </form>
  <% end %>
</div>


<script type="text/javascript">
  $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

app/views/pages/edit_discharge.html.erb
<div class="container">
  <% if @recordLocation == "discharge" %>
  <form action="/pages/<%= @patient.id %>/update/update_discharge" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <p><%= debug @discharge %></p>
      <label>Date</label>
       <input type="text" class="form-control datepicker" name="discharge[date]" value="<%= @patient.discharge.date %>">
    </div>
    
    <div class="form-group">
      <label>Time</label>
        <div class='input-group date' id="datetimepicker3">
            <input type="text" class="form-control timepicker" name="discharge[time]" value="<%= @patient.discharge.time.strftime("%I:%M%p")%>">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-time"></span>
            </span>
        </div>
    </div>
    
    <div class="form-group">
      <div class="button_choose_show_action">
        <p><input type="submit" class="btn btn-primary" style="margin-right: 10px;" value="Update"></p>
        <p><%= link_to "Back", page_path(@patient), html_options = {class: "btn btn-success"} %></p>
      </div>
    </div>
  </form>
  <% end %>
</div>


<script type="text/javascript">
  $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  $('.timepicker').datetimepicker({format: 'LT'});
</script>

app/views/pages/edit_dr_note.html.erb
<h2>Doctor's Note:</h2>

<%= simple_form_for [:pages, @patient, @treatment, @dr_note], url: update_dr_note_path do |dr_note| %>
  <%= dr_note.input :name %>
  <%= dr_note.input :message %>
  <%= dr_note.button :submit %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/pages/edit_location.html.erb
<div class="container">
  <% if @recordLocation == "location" %>
  <form action="/pages/<%= @patient.id %>/update/update_location" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      
    <div class="form-group">
      <p><%= debug @location %></p>
      <label>Facility</label>
       <input type="text" class="form-control" name="location[facility]" value="<%= @patient.location.facility %>">
    </div>
    
    <div class="form-group">
      <label>Room</label>
       <input type="text" class="form-control" name="location[room]" value="<%= @patient.location.room %>">
    </div>
      
    <div class="form-group">
      <label>Bed</label>
       <input type="text" class="form-control" name="location[bed]" value="<%= @patient.location.bed %>">
    </div>
      
    <div class="form-group">
      <label>Visitor Limit</label>
       <input type="text" class="form-control" name="location[visitor_limit]" value="<%= @patient.location.visitor_limit %>">
    </div>
      
    <div class="form-group">
      <label>Approved Visitors</label>
       <input type="text" class="form-control" name="location[approved_visitors]" value="<%= @patient.location.approved_visitors %>">
    </div>
    
    <div class="form-group">
      <div class="button_choose_show_action">
        <p><input type="submit" class="btn btn-primary" style="margin-right: 10px;" value="Update"></p>
        <p><%= link_to "Back", page_path(@patient), html_options = {class: "btn btn-success"} %></p>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/pages/edit_patient.html.erb
<h2 class="foo">Edit Page Patient Light </h2>

<div class="container">
  <% if @recordLocation == "general" %>
  <form action="/pages/<%= @patient.id %>/update/update_patient" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <div class="form-group">
      <label>Last Name</label>
      <input type="text" class="form-control" name="patient[last_name]" value="<%= @patient.last_name %>">
    </div>
    
    <div class="form-group">
      <label>First Name</label>
      <input type="text" class="form-control" name="patient[first_name]" value="<%= @patient.first_name %>">
    </div>
    
    <div class="form-group">
      <label>Middle Name</label>
      <input type="text" class="form-control" name="patient[middle_name]" value="<%= @patient.middle_name %>">
    </div>
    
    <div class="form-group">
      <label>Birthday</label>
      <input type="text" class="form-control datepicker" name="patient[birthday]" value="<%= @patient.birthday %>">
    </div>
    
    <div class="form-group">
      <div class="button_choose_show_action">
        <p><input type="submit" class="btn btn-primary" style="margin-right: 10px;" value="Update"></p>
        <p><%= link_to "Back", page_path(@patient), html_options = {class: "btn btn-success"} %></p>
      </div>
    </div>
  </form>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
    $('.timepicker').datepicker({format: 'HH:mm:ss'});
  });
</script>

app/views/pages/edit_physician.html.erb
<div class="container">
  <% if @recordLocation == "physician" %>
  <form action="/pages/<%= @patient.id %>/update/update_physician" method="post">
    <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      
    <div class="form-group">
      <p><%= debug @physician %></p>
      <label>Physician Name</label>
       <input type="text" class="form-control" name="physician[family_physician]" value="<%= @patient.physician.family_physician %>">
    </div>
    
    <div class="form-group">
      <label>Physician Phone</label>
       <input type="text" class="form-control" name="physician[physician_phone]" value="<%= @patient.physician.physician_phone %>">
    </div>
    
    <div class="form-group">
      <div class="button_choose_show_action">
        <p><input type="submit" class="btn btn-primary" style="margin-right: 10px;" value="Update"></p>
        <p><%= link_to "Back", page_path(@patient), html_options = {class: "btn btn-success"} %></p>
      </div>
    </div>
  </form>
  <% end %>
</div>

app/views/pages/edit_schedule.html.erb
 <h2>Edit Schedule:</h2>

<%= simple_form_for [:pages, @patient, @treatment, @schedule], url: update_schedule_path do |schedule| %>
  <%= schedule.input :date, as: :string, required: true, input_html: {class: "datepicker"} %>
  <%= schedule.input :time, as: :string, required: true, input_html: {class: "timepicker"} %>
  <%= schedule.input :schedule_msg %>
  <%= schedule.button :submit %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/pages/new.html.erb
<h1>New Patient</h1>

<%= simple_form_for @patient, url: {action: "create"} do |f| %>
  <%= f.input :last_name, label: "Last Name" %>
  <%= f.input :first_name, label: "First Name" %>
  <%= f.input :middle_name, label: "Middle Name" %>
  <%= f.input :birthday, as: :string, label: "birthday", required: false, input_html: {class: "datepicker", value: Date::strptime("1990-01-20", "%Y-%m-%d")} %>
  <%= f.submit :submit %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker({format: 'yyyy-mm-dd'});
  });
</script>

app/views/pages/new_charge.html.erb
<h2>Create a New Charge:</h2>
<%= simple_form_for @patient.discharge.bill.charges.build, url: new_charge_path do |f| %>
    <%= f.input :charge_name %>
    <%= f.input :charge_amount %>
    <%= f.submit :submit %>
<% end %>

app/views/pages/new_contact.html.erb
<h2>New Contact Information</h2>
<div class = "container">
  <%= simple_form_for @patient.build_contact, url: new_contact_path do |f| %>
    <%= f.input :home_phone %>
    <%= f.input :work_phone %>
    <%= f.input :mobile_phone %>
    <%= f.input :street %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :zip %>
    <%= f.submit :submit %>
  <% end %>
</div>

app/views/pages/new_prescription.html.erb
<h2>Create a Prescription:</h2>
<%= simple_form_for @patient.treatment.prescriptions.build, url: new_prescription_path do |f| %>
    <%= f.input :name %>
    <%= f.input :amount %>
    <%= f.input :schedule %>
    <%= f.submit :submit %>
<% end %>

app/views/pages/new_treatment.html.erb
<div class="container">
  <h2>New Treatment Information</h2>
  <%= simple_form_for @patient.build_treatment, url: create_treatment_path, controller: 'pages', action: 'create_treatment' do |f| %>
    <%= f.input :name %>
    <%= f.submit :submit %>
  <% end %>
</div>

app/views/pages/pagesPatientResults.html.erb
<% require_relative('./HelperDisplayFunctions') %>

<div class="patientResultsWrapper">
  <h2 class="center-text">Patients that matched your search criteria</h2>
  <p class="go_back"> <%= link_to "Back", :back %></p>

  <% @patients.first(10).each do |patient| %>
    <div class="patient-card">
      <h3><%= patient.first_name + "  " + patient.last_name %></h3>
      <div>
        <p>Basic Info</p>
        <div class="patient-info-div">
          <p> facility: <%= HelperDisplay.facilitytry(patient.location) %> </p>
          <p> room: <%= HelperDisplay.roomtry(patient.location) %> </p>
          <p> bed: <%= HelperDisplay.bedtry(patient.location) %> </p> <br>
        </div>
        <p>View Complete Profile</p>
        <p class="view-more"><%= link_to "View More", page_path(patient) %></p>
      </div>
    </div>
  <% end %>
</div>



app/views/pages/patientSearchPage.html.erb
   <% accessVar = "" %>
   <% imagePath = '' %>
   <% if current_user.doctor_role %>
     <% accessVar = "doctor" %>
     <% imagePath = 'doctorStaff.jpg' %>
   <% end %>
   <% if current_user.medical_role %>
     <% accessVar = "medical" %>
     <% imagePath = 'medicalStaff.jpg' %>
   <% end %>
   <% if current_user.office_role %>
     <% accessVar = "office" %>
     <% imagePath = 'officeStaff.jpg' %>
   <% end %>
   <% if current_user.volunteer_role %>
     <% accessVar = "volunteer" %>
     <% imagePath = 'volunteerStaff.jpg' %>
   <% end %>

  <div class="container">
   <div class="searchPageWrapper">
		<div class="info_boxes" id="info_box1">
      <h1 class = "header">Patient Search Screen</h1>
      
      <hr class="divLine">

		</div>
		
		<div class="info_boxes" id="info_box2">
			<div class="patient_box">
        <div class="form-group">    
        <p> Enter a First or Last Name </p>           
        <%= form_tag pages_patient_results_path, :method => 'get' do %>
        <p>
          <%= text_field_tag :search %>
          <%= submit_tag "Search" %>
        </p>
        <% end %>

        </div>
      </div>
    </div>
    
   

		<div class="info_boxes" id="info_box3">			
			<div class="form-group search_button_div">
        <% if !current_user.superadmin_role? %>
          <p> Search All Patients</p><br>
          <%= link_to "Find Patients", {controller: "pages", action: "index"}, class: "btn btn-small btn-success" %>
        <% end %>
                
        <% if accessVar == "office"%>
          <div class="office_worker_message">
            <p>If you need to add a new patient instead, click the link below</p>
            <div class="form-group">
              <%= link_to "Add New Patient", new_page_path %>
            </div>
          </div>
        <% end %>
        <div class="welcome_box">
          <p> <%= current_user.email %> </p>
          <p>Access Rights: <span id="access_rights"> <%= accessVar %> </span></p>
        </div>             
			</div>
		</div>
	</div>